### ISSUE TITLE
Starting docker ozone project

### ISSUE THREAD

**Issue by rsoika** [flokkr/flokkr#1]
Hi,
I try to get started with hadoop ozone. I want to develop a project based on ozone. 

There for I try to setup a dev environment with docker. I followed this wiki:

https://cwiki.apache.org/confluence/display/HADOOP/Getting+Started+with+docker

But ksm is not starting and I see the following error messages in the log files:

```
ksm_1       | STARTUP_MSG:   build = https://github.com/apache/hadoop.git -r 034f01a9700e75146ed264625354810893f5fd14; compiled by 'jenkins' on 2017-10-11T21:35Z
ksm_1       | STARTUP_MSG:   java = 1.8.0_121
ksm_1       | ************************************************************/
ksm_1       | 2017-11-16 22:40:40 INFO  KeySpaceManager:51 - registered UNIX signal handlers for [TERM, HUP, INT]
ksm_1       | 2017-11-16 22:40:41 INFO  CallQueueManager:84 - Using callQueue: class java.util.concurrent.LinkedBlockingQueue queueCapacity: 20000 scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler
ksm_1       | 2017-11-16 22:40:41 INFO  Server:1067 - Starting Socket Reader #1 for port 9862
ksm_1       | 2017-11-16 22:40:41 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
ksm_1       | 2017-11-16 22:40:41 ERROR KeySpaceManager:193 - Failed to start the KeyspaceManager.
ksm_1       | java.lang.NullPointerException
ksm_1       | 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
ksm_1       | 	at org.apache.hadoop.ozone.web.utils.OzoneUtils.getScmMetadirPath(OzoneUtils.java:256)
ksm_1       | 	at org.apache.hadoop.ozone.ksm.KSMMetadataManagerImpl.<init>(KSMMetadataManagerImpl.java:73)
ksm_1       | 	at org.apache.hadoop.ozone.ksm.KeySpaceManager.<init>(KeySpaceManager.java:106)
ksm_1       | 	at org.apache.hadoop.ozone.ksm.KeySpaceManager.main(KeySpaceManager.java:189)
ksm_1       | 2017-11-16 22:40:41 INFO  ExitUtil:210 - Exiting with status 1: java.lang.NullPointerException
ksm_1       | 2017-11-16 22:40:41 INFO  KeySpaceManager:51 - SHUTDOWN_MSG: 
ksm_1       | /************************************************************
ksm_1       | SHUTDOWN_MSG: Shutting down KeySpaceManager at 0ac9a9cba6e4/172.18.0.4
ksm_1       | ************************************************************/
ksm_1       | Process exited with exit code 1
ksm_1       | Process has been failed (exit code: 1), restarting after 70 seconds... (3/10)
```

Can you help me with this issue?

**Comment by ps-account** [comment]
I have exactly the same issue. The weird thing is that even though the ksm shuts down, the docker is still up, only the datanode docker really dies. There are no working services on ports 9874 9876 though, so the corresponding services in these running services did stop.

```
$ docker-compose ps
         Name                       Command               State                         Ports                      
-------------------------------------------------------------------------------------------------------------------
hadoopozone_datanode_1   /usr/local/bin/dumb-init - ...   Exit 1                                                   
hadoopozone_ksm_1        /usr/local/bin/dumb-init - ...   Up       0.0.0.0:9874->9874/tcp                          
hadoopozone_namenode_1   /usr/local/bin/dumb-init - ...   Up       0.0.0.0:50070->50070/tcp, 0.0.0.0:9870->9870/tcp
hadoopozone_scm_1        /usr/local/bin/dumb-init - ...   Up       0.0.0.0:9876->9876/tcp                          

```

**Comment by elek** [comment]
Starting Ozone in kubernetes:

https://www.youtube.com/watch?v=jIXndjHv5F8&list=PLCaV-jpCBO8UK5Ged2A_iv3eHuozzMsYv&index=8&t=0s
